[tasks.build]
description = "Build planeshift with version metadata"
run = """
SEMVER=v0.0.999
BUILD_DATE=$(gdate --utc +%FT%T.%3NZ)
GIT_COMMIT=$(git rev-parse HEAD)

go build -ldflags "-X planeshift/cmd.semVer=${SEMVER} -X planeshift/cmd.buildDate=${BUILD_DATE} -X planeshift/cmd.gitCommit=${GIT_COMMIT} -X planeshift/cmd.gitRef=/refs/tags/${SEMVER}" && \
./planeshift version | jq .
"""
